stages:
  - build

variables:
  APT_CACHE_DIR: apt-cache
  PIP_CACHE_DIR: pip-cache

cache:
  untracked: true
  paths:
    - apt-cache
    - pip-cache

build:
  stage: build
  image: python:3.11.1
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y asciidoc
    - python --version
    - pip --version
    - pip install Lektor -c constraints.txt
  script:
    - make build
  only:
    - master
